# Generated by Django 5.2.17 on 2026-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
