# Generated by Django 5.2.17 on 2026-08-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
